[workspace]
members = ["sail", "borealis", "common", "decoder_harness"]
default-members = ["sail", "borealis", "common"]

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
