[package]
name = "libarch-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
errctx = "1.0.0"
color-eyre = "0.6.2"
memmap2 = "0.7.1"

[dev-dependencies]
insta = "1.31.0"

[build-dependencies]
bindgen = "0.66.1"
cc = "1.0.82"
