[package]
name = "libarch-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
errctx = "1.0.0"
color-eyre = "0.6.2"
memmap2 = "0.6.2"

[dev-dependencies]
insta = "1.29.0"

[build-dependencies]
bindgen = "0.65.1"
cc = "1.0.79"
