[package]
name = "borealis"
version = "0.1.0"
edition = "2021"
authors = ["AVISI Research Group"]
description = "Sail frontend for GenSim"

[dependencies]
common = { path = "../common" }
sail = { path = "../sail" }
displaydoc = "0.2.3"
thiserror = "1.0.37"
color-eyre = { version = "0.6.2", default-features = false }
clap = { version = "4.0.29", features = ["derive"] }
bincode = "1.3.3"
deepsize = "0.2.0"

[dev-dependencies]
insta = "1.22.0"
serde_json = "1.0.89"
