[package]
name = "borealis"
version = "0.2.0"
edition = "2021"
authors = ["AVISI Research Group"]
description = "Sail frontend for GenSim"

[dependencies]
common = { path = "../common" }
sail = { path = "../sail" }
errctx = { git = "https://github.com/fmckeogh/errctx" }
displaydoc = "0.2.3"
thiserror = "1.0.38"
color-eyre = { version = "0.6.2", default-features = false }
clap = { version = "4.1.4", features = ["derive"] }
bincode = "1.3.3"
deepsize = "0.2.0"
serde_json = "1.0.92"
pretty_env_logger = "0.4.0"
log = "0.4.17"
num-bigint = { version = "0.4.3", features = ["serde"] }
once_cell = "1.17.0"
lz4_flex = "0.10.0"

[dev-dependencies]
insta = "1.26.0"
reqwest = { version = "0.11.14", default-features = false, features = ["blocking", "rustls-tls", "json"] }
serde = { version = "1.0.152", features = ["derive"] }
