[package]
name = "borealis"
version = "0.3.0"
edition = "2021"
authors = ["AVISI Research Group"]
description = "Sail frontend for GenSim"

[dependencies]
common = { path = "../common" }
sail = { path = "../sail" }

displaydoc = "0.2.4"
thiserror = "1.0.40"
errctx = "1.0.0"
color-eyre = { version = "0.6.2", default-features = false }
pretty_assertions = "1.3.0"
pretty_env_logger = "0.5.0"
log = "0.4.18"

clap = { version = "4.3.2", features = ["derive"] }

bincode = "1.3.3"
deepsize = "0.2.0"
serde_json = "1.0.96"
num-bigint = { version = "0.4.3", features = ["serde"] }
once_cell = "1.18.0"
lz4_flex = { version = "0.10", default-features = false, features = ["frame"]}
phf = { version = "0.11.1", features = ["macros"] }
regex = "1.8.4"
dot = "0.1.4"

[dev-dependencies]
insta = "1.29.0"
