[package]
name = "decoder_harness"
version = "0.1.0"
edition = "2021"

[dependencies]
errctx = { git = "https://github.com/fmckeogh/errctx" }

color-eyre = "0.6.2"
cxx = "1.0.88"
memmap2 = "0.5.8"

[build-dependencies]
cxx-build = "1.0.88"
